<?php
// $Id: uc_linkpoint_api.install,v 1.2 2009/06/26 18:32:02 jrust Exp $
/**
 * Implementation of hook_uninstall().
 */
function uc_linkpoint_api_uninstall() {
  variable_del('firstdata_gateway_login_id');
  variable_del('firstdata_gateway_login_pw');
  variable_del('firstdata_gateway_transaction_cert');
  variable_del('firstdata_gateway_transaction_key');
  variable_del('firstdata_gateway_transaction_pw');
}

